# Generated by Django 4.0.6 on 2022-07-26 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='fabricante',
        ),
        migrations.AddField(
            model_name='producto',
            name='fabricante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fabricante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
