# Generated by Django 4.0.6 on 2022-07-26 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0004_alter_producto_fabricante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabricante', to=settings.AUTH_USER_MODEL),
        ),
    ]
