# Generated by Django 4.0.6 on 2022-07-26 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0005_alter_producto_fabricante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='detalle',
        ),
        migrations.AddField(
            model_name='detalle',
            name='compra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fabricante', to='marketApp.compra'),
        ),
    ]
