# Generated by Django 4.0.6 on 2022-08-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0006_remove_compra_detalle_detalle_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle',
            old_name='precio',
            new_name='precioTotal',
        ),
        migrations.AddField(
            model_name='detalle',
            name='precioUnidad',
            field=models.FloatField(default=0),
        ),
    ]
