# Generated by Django 4.0.6 on 2022-08-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0007_rename_precio_detalle_preciototal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
