# Generated by Django 4.0.6 on 2022-08-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0009_alter_detalle_compra_remove_detalle_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='generic', max_length=300, verbose_name='NombreProducto'),
        ),
    ]
